"use client";

import { Leaf, BadgeCheck, Zap } from "lucide-react";

export default function Dashboard({ match }: { match: any }) {
  if (!match) {
    return (
      <div className="bg-neutral-900 border border-neutral-800 rounded-xl p-8 text-center flex flex-col items-center justify-center opacity-50 shadow-2xl h-full backdrop-blur-md bg-opacity-70">
        <Leaf size={48} className="text-neutral-700 mb-4" />
        <h3 className="text-xl font-bold text-neutral-400">No Active Matches</h3>
        <p className="text-neutral-500 max-w-sm mt-2">The system is continuously scanning for industrial symbiosis opportunities.</p>
      </div>
    );
  }

  return (
    <div className="bg-neutral-900 border border-emerald-900/50 flex flex-col h-full rounded-xl overflow-hidden shadow-2xl animate-fade-in backdrop-blur-md bg-opacity-70">
      <div className="bg-emerald-950/30 p-4 border-b border-emerald-900/50 flex justify-between items-center">
        <h2 className="text-xl font-bold flex items-center text-emerald-400">
          <BadgeCheck className="mr-2" /> Match Successful
        </h2>
        <span className="text-xs font-mono bg-emerald-500/10 text-emerald-400 px-3 py-1 rounded-full border border-emerald-500/20">
          {match.distance_km} km away
        </span>
      </div>
      
      <div className="p-6 flex-1 space-y-6 overflow-y-auto max-h-[600px]">
        {/* Parties */}
        <div className="grid grid-cols-2 gap-4">
          <div className="bg-neutral-950 p-4 rounded-lg border border-neutral-800">
            <span className="text-xs text-neutral-500 uppercase font-bold tracking-wider">Producer</span>
            <p className="font-bold mt-1 text-lg text-rose-400">{match.producer.name}</p>
            <p className="text-neutral-400 text-sm mt-2 bg-neutral-900 p-2 rounded">Waste: {match.waste.quantity} {match.waste.unit} of {match.waste.waste_type}</p>
          </div>
          <div className="bg-neutral-950 p-4 rounded-lg border border-neutral-800">
            <span className="text-xs text-neutral-500 uppercase font-bold tracking-wider">Consumer</span>
            <p className="font-bold mt-1 text-lg text-blue-400">{match.consumer.name}</p>
            <p className="text-neutral-400 text-sm mt-2 bg-neutral-900 p-2 rounded line-clamp-2" title={match.consumer.demand}>Demand: {match.consumer.demand}</p>
          </div>
        </div>

        {/* Agreement generated by Negotiator LLM */}
        <div className="bg-neutral-950 rounded-lg border border-neutral-800 p-5">
           <h3 className="text-sm text-neutral-500 uppercase font-bold tracking-wider mb-3">AI-Drafted Agreement</h3>
           <p className="text-neutral-300 font-medium mb-4 italic text-sm border-l-2 border-neutral-700 pl-3">"{match.agreement.agreement_summary}"</p>
           <div className="flex justify-between items-center bg-neutral-900 rounded p-3 text-sm">
             <span className="text-neutral-400">Transport: <span className="text-amber-400 font-mono font-bold">{match.agreement.estimated_transport_cost}</span></span>
             <span className="text-neutral-400">Timeline: <span className="text-emerald-400 font-mono font-bold">{match.agreement.timeline}</span></span>
           </div>
        </div>

        {/* ESG Pitch generated by Evaluator LLM */}
        <div className="bg-emerald-950/20 rounded-lg border border-emerald-900/30 p-5">
           <h3 className="text-sm flex items-center text-emerald-500 uppercase font-bold tracking-wider mb-3">
             <Zap size={16} className="mr-1" /> Sustainability Impact
           </h3>
           <p className="text-neutral-300 text-sm leading-relaxed">{match.sustainability_pitch}</p>
        </div>
      </div>
    </div>
  );
}
